version: "3.5"
services:
  postgres:
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - /portainer/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    platform: linux/x86_64
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    build: .
    ports:
      - 3005:3005
    volumes:
      - /portainer/linkwarden/data:/data/data
    depends_on:
      - postgres
