version: "3.5"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /portainer/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    build: .
      dockerfile: Dockerfile
    restart_policy:
      condition: on-failure
    ports:
      - 3005:3005
    volumes:
      - /portainer/linkwarden/data:/data/data
    depends_on:
      - postgres
